### ISSUE TITLE
tagged release with ffmpeg plugin support for the OpenVisualCloud docker images

### ISSUE THREAD

**Issue by mash-graz** [OpenVisualCloud/SVT-VP9#103]
could you please think about publishing another tagged release of  SVT-VP9, to make the vp9 ffmpeg-plugin finally easier accessible in the OpenVisualCloud docker images to a wider audience.

see also:  https://github.com/OpenVisualCloud/Dockerfiles/issues/387 from february

**Comment by tianjunwork** [comment]
Done. It is included in the latest Dockerfiles release.
