### ISSUE TITLE
Build failed on fresh debian 9 install

### ISSUE THREAD

**Issue by ndeans123** [OpenVisualCloud/SVT-VP9#106]
I can't seem to get SVT-VP9 to build on a fresh Debian 9 install.  I am using the following instructions:

git clone https://github.com/OpenVisualCloud/SVT-VP9
cd SVT-VP9
cd Build && cmake .. && make -j nproc && sudo make install

And at the make -j part I receive this:

CMakeFiles/Makefile2:310: recipe for target 'Source/Lib/ASM_SSSE3/CMakeFiles/VP9_ASM_SSSE3.dir/all' failed
make[1]: *** [Source/Lib/ASM_SSSE3/CMakeFiles/VP9_ASM_SSSE3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 59%] Built target VP9_ASM_SSE4_1
[ 59%] Built target VP9_C_DEFAULT
CMakeFiles/Makefile2:255: recipe for target 'Source/Lib/ASM_SSE2/CMakeFiles/VP9_ASM_SSE2.dir/all' failed
make[1]: *** [Source/Lib/ASM_SSE2/CMakeFiles/VP9_ASM_SSE2.dir/all] Error 2
[ 59%] Built target libVPX
[ 59%] Built target VP9_ASM_AVX2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Here is the full output: https://pastebin.com/4C3ei4C7

This is a brand new install of Debian 9, with cmake 3.7.2-1, gcc 6.3.0-18 and yasm 1.3.0-2

I also tried this on Ubuntu 18.04 before and it was the same errors.   Maybe I am just doing something wrong?  Any hints here?  I've tried with root and without also.

**Comment by 1480c1** [comment]
What nasm version?

**Comment by ndeans123** [comment]
> What nasm version?

root@78C322E:~/SVT-VP9/Build# nasm -v
NASM version 2.12.01

**Comment by 1480c1** [comment]
Your cmake picked up nasm first, and in certain nasm versions, the include argument is "broken"

**Comment by 1480c1** [comment]
Try passing `-DCMAKE_ASM_NASM_COMPILER=yasm` to your cmake line, so `cmake .. -DCMAKE_ASM_NASM_COMPILER=yasm`

**Comment by ndeans123** [comment]
Ah, my mistake, I yasm wasn't actually installed, so I'm assuming it didn't pick up on it and went to nasm?  Anyway, I installed yasm and it is working now.

**Comment by 1480c1** [comment]
That's good

**Comment by ndeans123** [comment]
Thanks for the help
