### ISSUE TITLE
ffmpeg_plugin fails to apply against n4.2.3

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-VP9#108]
Regressed by https://github.com/ffmpeg/ffmpeg/commit/477275795865 and https://github.com/ffmpeg/ffmpeg/commit/7f2ab227e038.

```
$ cd ffmpeg
$ git checkoun n4.2.3

$ patch -CEfsp1 -i ../SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
2 out of 8 hunks failed while patching libavformat/matroskaenc.c

$ git apply ../SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
error: patch failed: libavformat/matroskaenc.c:2401
error: libavformat/matroskaenc.c: patch does not apply
```

**Comment by tianjunwork** [comment]
Yeah, this is a known issue. Originally with master, now with 4.2.3. Thanks reporting. We will fix it.

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925, could you make a patch for ffmpeg 4.2.3 release tag? Let's keep the 4.2.2 patch also. In case community still uses it. Please label the patch and update README in ffmpeg folder.  #92 can be removed. Thank you.
