### ISSUE TITLE
a bug in ffmpeg wrapper(libsvt_vp9.c)

### ISSUE THREAD

**Issue by XuShiSheng** [OpenVisualCloud/SVT-VP9#110]
we exit encoding in ffmpeg by testing if flag == EB_BUFFERFLAG_EOS, but some time the last frame's flag is EB_BUFFERFLAG_SHOW_EXT | EB_BUFFERFLAG_EOS in this case ffmpeg will hang in function eb_receive_packet.

**Comment by tianjunwork** [comment]
Hi @XuShiSheng , could you share more information about how you use svt-vp9?
Is it by calling ffmpeg libraries? or through ffmpeg cli? It is confusing to me that either EB_BUFFERFLAG_SHOW_EXT or EB_BUFFERFLAG_EOS is exposed beyond svt-vp9 plugin.
Add @guojiansheng0925 in the discussion.

**Comment by XuShiSheng** [comment]
Hi, I use it through ffmpeg cli. 
please refer to line 482 in ffmpeg_plugin patch
[https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch](url)

**Comment by tianjunwork** [comment]
Could you share the cli?

**Comment by tianjunwork** [comment]
@guojiansheng0925 https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch#L482  `if (EB_BUFFERFLAG_EOS == headerPtr->flags)` can be changed to `if (EB_BUFFERFLAG_EOS & headerPtr->flags)`, since @XuShiSheng is reporting sometimes the flag is `EB_BUFFERFLAG_SHOW_EXT | EB_BUFFERFLAG_EOS` for last frame.

**Comment by XuShiSheng** [comment]
sorry for the late reply. @tianjunwork 

ffmpeg cli
`./ffmpeg -i input -r 30/1 -vsync 2  -copyts -filter_complex "[0]scale=w=960:h=544:flags=lanczos[scale_1_out]" -map [scale_1_out]:v? -an  -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_trc iec61966-2-1 -color_range 0  -vcodec libsvt_vp9  -preset 9 -rc 2  -vb 2300k  output.mp4`

and test seq
[https://share.weiyun.com/fPZbLH6k](testseq)

**Comment by guojiansheng0925** [comment]
Hi @XuShiSheng , thank you for sharing your command line and test seq. I can reproduce the issue and I have revised the ffmpeg plugin patch with @tianjunwork 's suggestion.
