### ISSUE TITLE
Error compiling with FFMPEG

### ISSUE THREAD

**Issue by bentotom** [OpenVisualCloud/SVT-VP9#113]
Running into an issue while compiling ffmpeg with autobuild suite.

using latest git from an hour ago.
and master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch

tail of log

```
E:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_vp9.c: In function 'config_enc_params':
E:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_vp9.c:191:10: error: 'EbSvtVp9EncConfiguration' has no member named 'intra_refresh_type'
  191 |     param->intra_refresh_type       =
      |          ^~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:59: libavcodec/libsvt_vp9.o] Error 1
```

**Comment by 1480c1** [comment]
Autobuild suite issues should get reported to the suite unless it's explicitly an issue with upstream.

**Comment by tianjunwork** [comment]
Hi @bentotom, do you have the same issue with ffmpeg upstream?

**Comment by bentotom** [comment]
Not sure what you mean by upstream.
I'm able to build without svtvp9. Only adding vp9 + patch results in this error.
Using the non master patch results in errors during patch.

**Comment by tianjunwork** [comment]
I mean using ffmpeg upstream directly just as what is described in https://github.com/OpenVisualCloud/SVT-VP9/tree/master/ffmpeg_plugin.

**Comment by bentotom** [comment]
Unfortunately I don't have the appropriate development environment set up to build.

Is this only tested with 4.2.2? Should I be pulling that instead of the latest version?

**Comment by tianjunwork** [comment]
```
Note: patches for FFmpeg n4.2.3/master are alse provided:

n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
```
It also supports 4.2.3 and master.

**Comment by bentotom** [comment]
I've been running the master patch as noted above. The other 2 patches throw errors during configure.

**Comment by 1480c1** [comment]
It seems that intra_refresh_type was removed from the public API, but that removal was not reflected in the patches

https://github.com/OpenVisualCloud/SVT-VP9/commit/7ff45ce33b74eaee443dce4b4748909d732458d2

**Comment by bentotom** [comment]
@1480c1 
I believe the patches reflect the change. The latest version from this morning doesen't have that variable.
Running a diff against the 2 files gives
`++
++    param->intra_refresh_type       =
++        !!(avctx->flags & AV_CODEC_FLAG_CLOSED_GOP) + 1;
 +`

**Comment by 1480c1** [comment]
It seems only the master patch still contains it

**Comment by bentotom** [comment]
any thoughts on how I can get it to patch?

**Comment by 1480c1** [comment]
Removed it in the modified patch, rerun the suite

**Comment by bentotom** [comment]
Ran into a different error. But thanks for the quick fix on the patch file.

`AR	libavcodec/libavcodec.a
E:\media-autobuild_suite-master\msys64\mingw64\bin\ar.exe: libavcodec/libaomdec.o: No such file or directory

make: *** [/build/ffmpeg-git/ffbuild/library.mak:22: libavcodec/libavcodec.a] Error 1
CC	libavcodec/libaomdec.o
AR	libavcodec/libavcodec.a
LD	ffmpeg_g.exe
E:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:/media-autobuild_suite-master/msys64/mingw64/lib/libxvidcore.a(mbcoding.obj):(.text+0x41a0): multiple definition of `get_mv'; E:/media-autobuild_suite-master/local64/lib/libSvtVp9Enc.a(EbMotionEstimationProcess.c.obj):EbMotionEstimationProcess.c:(.text+0xef0): first defined here

collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:114: ffmpeg_g.exe] Error 1`

**Comment by 1480c1** [comment]
a lot of functions needs to be cleaned up in the svt codebase, I would recommend disabling libxvid for now

**Comment by bentotom** [comment]
Awesome. That did the trick.
Thanks for all the help!
