### ISSUE TITLE
FFmpeg-master: patch needs rebasing

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-VP9#145]
There seems to be a conflict in matroskaenc and I do not know enough about what exactly was done to change it

**Comment by dbermond** [comment]
I have prepared a working patch (works for me at least):

https://aur.archlinux.org/cgit/aur.git/tree/040-ffmpeg-add-svt-vp9.patch?h=ffmpeg-full-git

**Comment by dbermond** [comment]
This is the upstream ffmpeg commit that broke the patch:

https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=b972dab39d81d5f291cea4b9a042beb63386e768

**Comment by tianjunwork** [comment]
Hi Jiansheng, @guojiansheng0925, could you rebase the patch for master? Thank you.

**Comment by guojiansheng0925** [comment]
Hi @tianjunwork , the patch for master branch is rebased.
Could you please help to review the PR, thanks.
