### ISSUE TITLE
FFmpeg patch not working

### ISSUE THREAD

**Issue by krychu90** [OpenVisualCloud/SVT-VP9#153]
When I try to patch the latest ffmpeg version then error occurs:
```
$ git apply ../SVT-VP9/ffmpeg_plugin/master-0001-Add-ability-for -ffmpeg-to-run-svt-vp9.patch
error: patch failed: configure:1832
error: configure: patch does not apply
```

**Comment by krychu90** [comment]
My ffmpeg version is:
_ffmpeg version N-105824-g4419433d77_

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925 , the master* patch doesn't apply on FFmpeg master. Could you address it? Thank you.
