### ISSUE TITLE
Does this work on AWS or GCE?

### ISSUE THREAD

**Issue by colleenkhenry** [OpenVisualCloud/SVT-VP9#16]
Does this work on AWS or GCE instances or does it need some sort of lower level access than they provide for the "scalable" part of the Xeons?

**Comment by tianjunwork** [comment]
Hi @colleenkhenry the encoder can run on AWS as long as the platform meets the need of System Requirements in https://github.com/OpenVisualCloud/SVT-VP9/blob/master/README.md. It doesn't need anything more than that.

**Comment by colleenkhenry** [comment]
Thanks!
