### ISSUE TITLE
Decoder not found

### ISSUE THREAD

**Issue by hhazjXS** [OpenVisualCloud/SVT-VP9#166]
provide?

**Comment by 1480c1** [comment]
At this time, SVT-VP9 lacks developer resource to provide any new feature updates, and additionally, there already exists well-developed VP9 decoders such as ffvp9 from FFmpeg and the reference decoder from libvpx

https://blogs.gnome.org/rbultje/2015/09/28/vp9-encodingdecoding-performance-vs-hevch-264/  shows some comparisons between the two decoders and a few others.
