### ISSUE TITLE
Defining a "Scalable" processor?

### ISSUE THREAD

**Issue by colleenkhenry** [OpenVisualCloud/SVT-VP9#19]
Sorry to ask more questions. 

If I understand right, the "scalable processor" performance optimizations exist within Skylake-SP xeon processors and up. 

If I am correct in that, I presume that a Xeon W-2195 is NOT an ideal processor for running this software on.

Can you confirm? Thank you again!

**Comment by tianjunwork** [comment]
The scalable technology in "**Scalable** Video Technology" doesn't depend on the "**scalable** processor".
Actually, the performance of encoder is depend on the Instruction Set Extensions of your CPU. To get accelerated speed, you'd better have AVX-512.
To learn more about the **Scalable** Video Technology, please refer to white paper here: https://01.org/svt

**Comment by tianjunwork** [comment]
You can run it on Xeon W-2195. 
SVT is designed to use as much computation power as possible, so with a more powerful CPU(e.g. xeon 8180), you get less latency.
