### ISSUE TITLE
ffmpeg plugin does not support b-frames

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-VP9#2]
Signalling invisible frames is not working properly with svt-vp9 ffmpeg plugin

**Comment by colleenkhenry** [comment]
Do you really mean b-frames? Vp9 doesn't have b frames... 

Are you meaning alt-ref frames?

**Comment by jsunintel** [comment]
I worked out a temp fix as below and it worked well.

diff --git a/libavcodec/vp9_superframe_bsf.c b/libavcodec/vp9_superframe_bsf.c
index ea67507..8bf6031 100644
--- a/libavcodec/vp9_superframe_bsf.c
+++ b/libavcodec/vp9_superframe_bsf.c
@@ -24,7 +24,7 @@
 #include "bsf.h"
 #include "get_bits.h"

-#define MAX_CACHE 8
+#define MAX_CACHE 32
 typedef struct VP9BSFContext {
     int n_cache;
     AVPacket *cache[MAX_CACHE];

FFmpeg tried to find a cache and handled the invisible frame package on it, after a package was received from SVT VP9 lib. And apperantly 8 caches for superframe bs filtering were not enough for SVT VP9. @hassount do you think there might be some underline performance issue in SVT VP9 lib or in the plugin?

**Comment by tianjunwork** [comment]
Hi @hassount, after get bit frame eb_svt_get_packet(component_handle, &header_ptr, pic_send_done), which flag indicates the frame is invisible? GStreamer has the same issue. Only visible frame is played back.

**Comment by jsunintel** [comment]
> 
> 
> I worked out a temp fix as below and it worked well.
> 
> diff --git a/libavcodec/vp9_superframe_bsf.c b/libavcodec/vp9_superframe_bsf.c
> index ea67507..8bf6031 100644
> --- a/libavcodec/vp9_superframe_bsf.c
> +++ b/libavcodec/vp9_superframe_bsf.c
> @@ -24,7 +24,7 @@
> #include "bsf.h"
> #include "get_bits.h"
> 
> -#define MAX_CACHE 8
> +#define MAX_CACHE 32
> typedef struct VP9BSFContext {
> int n_cache;
> AVPacket *cache[MAX_CACHE];
> 
> FFmpeg tried to find a cache and handled the invisible frame package on it, after a package was received from SVT VP9 lib. And apperantly 8 caches for superframe bs filtering were not enough for SVT VP9, and that was caused by the long latency between send_frame & receive_pkg returning with a finished frame by lib.
> 
> @hassount do you think there might be some underline performance issue in SVT VP9 lib, or does the plugin tend to trigger the encoding tasks in lab too late (only when the last frame is sent or the internal FIFOs in lib run out)?

This one is not the correct solution. Please refer to https://github.com/OpenVisualCloud/SVT-VP9/issues/27
