### ISSUE TITLE
Question: Dual or single Gold 

### ISSUE THREAD

**Issue by colleenkhenry** [OpenVisualCloud/SVT-VP9#21]
In the readme I see 

"The SVT-VP9 Encoder is being optimized to achieve excellent performance levels currently supporting 10 density-quality presets (please refer to the user guide for more details) on a system with a dual Intel® Xeon® Scalable processor targeting:

Real-time encoding of up to two 4Kp60 streams on the Gold 6140 with M8."

I can't tell from the second part if you mean dual gold 6140 CPUs or just a single one. Can you advise?

**Comment by tianjunwork** [comment]
"on a system with a dual Intel® Xeon® Scalable processor" ==> means that a dual-socket system, each of which is a Xeon Scalable processor.
Branch mark is done on dual-socket system with Xeon 6140 processor. So two 6140 processors.

**Comment by colleenkhenry** [comment]
Thanks!
