### ISSUE TITLE
ffmpeg patch svt-vp9/svt-av1/svt-hevc

### ISSUE THREAD

**Issue by philtems** [OpenVisualCloud/SVT-VP9#24]
Any chance to have a patch for ffmpeg working together with svt-av1 and svt-hevc?

**Comment by tianjunwork** [comment]
Hi @jsunintel, could you help on this? Thx.

**Comment by jsunintel** [comment]
> 
> 
> Any chance to have a patch for ffmpeg working together with svt-av1 and svt-hevc?

Already done:

- git clone https://github.com/FFmpeg/FFmpeg ffmpeg
- cd ffmpeg
- git checkout release/4.1
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
- export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
If no SVT-HEVC plugin in FFmpeg
- git apply ../SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
- ./configure --enable-libsvtav1
Or if based on the SVT-HEVC plugin patch in FFmpeg
- git apply ../SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ./configure --enable-libsvthevc (optional) --enable-libsvtav1
- make -j `nproc`

**Comment by colleenkhenry** [comment]
Is it just me or does that not include Vp9?

**Comment by jsunintel** [comment]
> 
> 
> Is it just me or does that not include Vp9?

"Any chance to have a patch for ffmpeg working together with svt-av1 and svt-hevc?"
The question did not mention VP9. I will try to add that support if you need it.

**Comment by colleenkhenry** [comment]
Isn't this the Vp9 repo? :)?

**Comment by jsunintel** [comment]
It just occured to me that the third lib would complicate the problem, and my plan is:

Currently:
SVT-HEVC: one plugin patch A#.
SVT-AV1: two plugin patches, B# to be applied alone, C# to be applied on the top of A#.

After adding SVT-VP9,
SVT-HEVC: one plugin patch A#.
SVT-AV1: two plugin patches, B# to be applied alone, C# to be applied on the top of A#.
SVT-VP9: two plugin patches, D# to applied alone, E# to be applied on the top of A# and C#.

And the combination AV1+VP9 & HEVC+VP9 will not be supported.

**Comment by philtems** [comment]
> It just occured to me that the third lib would complicate the problem, and my plan is:
> 
> Currently:
> SVT-HEVC: one plugin patch A#.
> SVT-AV1: two plugin patches, B# to be applied alone, C# to be applied on the top of A#.
> 
> After adding SVT-VP9,
> SVT-HEVC: one plugin patch A#.
> SVT-AV1: two plugin patches, B# to be applied alone, C# to be applied on the top of A#.
> SVT-VP9: two plugin patches, D# to applied alone, E# to be applied on the top of A# and C#.
> 
> And the combination AV1+VP9 & HEVC+VP9 will not be supported, to avoid too many versions of patches.

This sounds good. Too many combinations would be just confusing.

I'm working on a Ubuntu PPA similar to https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4
Idea is to add the 3 SVT libs and most common features.
I noticed libaom is useless for the moment for encoding. Performances are really poor compared to SVT-AV1. The two other HEVC and VP9 give also a nice performance boost.

**Comment by jsunintel** [comment]
SVT-VP9 and SVT-AV1 have conflications. The same API header file names, and the same API function names. FFMPEG gets confused. Working on it.

**Comment by colleenkhenry** [comment]
I appreciate your clear technical direction. Thank you.
