### ISSUE TITLE
Pipeline support issues.

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-VP9#3]
As shown in the picture, is it possible to forget to modify the code?
![](http://thyrsi.com/t6/671/1550311131x2890211684.jpg)
The code needs to be modified to increase support.
@hassount

**Comment by hassount** [comment]
@tnti 
Agreed, will update asap

**Comment by tianjunwork** [comment]
@tnti Pull request #10 fix this issue. You can apply this patch if it blocks you.
Thanks for posting the issue.

**Comment by tnti** [comment]
Thank you. @tianjunwork
