### ISSUE TITLE
-lp parameter (Logical Processor number) does not work

### ISSUE THREAD

**Issue by techvintage** [OpenVisualCloud/SVT-VP9#37]
CommadLine BKC section mentions:
LogicalProcessorNumber (-lp) and TargetSocket (-ss) parameters can be used to management the threads. Or you can use OS commands like below.
But on using -lp parameter,an error is returned mentioning 'Unprocessed token -lp'
Is thread management supported? If yes,can you share a working example to show how it works.

**Comment by tianjunwork** [comment]
Hi @techvintage, -lp and -ss is added for SVT-HEVC and SVT-AV1, not for VP9 yet.
The feature will be added soon.
