### ISSUE TITLE
960x540 resolution crash

### ISSUE THREAD

**Issue by Sorqan** [OpenVisualCloud/SVT-VP9#41]
I've been testing encoding at several different resolutions and I found that when trying to run specifically with `-w 960 -h 540` it doesn't start encoding and a few seconds later the app crashes.

I haven't found this to happen with any other resolution that I've tried so far.

**Comment by tianjunwork** [comment]
Hi @Sorqan is your master tip: Block input with non multiple of 8 resolution (#35)?
This patch block non multiple of 8 resolution which crashes the encoder lib.

**Comment by Sorqan** [comment]
I see I didn't do my research on this issue beforehand, thank-you for the quick answer.

**Comment by tianjunwork** [comment]
You're welcome:). We will add the support of non multiple of 8 resolution later.
