### ISSUE TITLE
Shared lib call exit

### ISSUE THREAD

**Issue by Vascom** [OpenVisualCloud/SVT-VP9#51]
I am try package svt-vp9 for Fedora and it has some warnings.

First of all compiled shared lib call exit. rpmlint message:
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.

Can you remove call exit?

**Comment by tianjunwork** [comment]
@Austin-Hu Could you remove exit() similar to SVT-HEVC does? Thank you.

**Comment by Austin-Hu** [comment]
Thanks for pointing this out, Vascom! Fixed with PR #56 , @tianjunwork .

**Comment by Vascom** [comment]
Verified.
Now good.
