### ISSUE TITLE
Unable to build SVT-VP9 ffmpeg plugin as static library

### ISSUE THREAD

**Issue by ariffinsetya** [OpenVisualCloud/SVT-VP9#55]
I've been trying to build SVT-VP9 as static ffmpeg plugin and I haven't been able to do so...
This is CMAKE vars that I used

> 
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_C_COMPILER = /usr/bin/gcc
-- CMAKE_ASM_NASM_COMPILER = /usr/bin/yasm
-- CMAKE_AR = /usr/bin/gcc-ar
-- CMAKE_RANLIB = /usr/bin/gcc-ranlib
-- CMAKE_INSTALL_PREFIX = /home/ariffinsetya/Workspace/ffmpeg-static/target
-- BUILD_SHARED_LIBS = off
>
and the errors i got is 
>
EbEncHandle.c.o (symbol from plugin): In function `lib_svt_encoder_send_error_exit':
(.text+0x0): multiple definition of `ignore_handler_s'
CMakeFiles/SvtVp9EncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `lib_svt_encoder_send_error_exit':
(.text+0x0): multiple definition of `invoke_safe_str_constraint_handler'
CMakeFiles/SvtVp9EncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `lib_svt_encoder_send_error_exit':
(.text+0x0): multiple definition of `strncpy_ss'
CMakeFiles/SvtVp9EncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `lib_svt_encoder_send_error_exit':
(.text+0x0): multiple definition of `strcpy_ss'
CMakeFiles/SvtVp9EncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `lib_svt_encoder_send_error_exit':
(.text+0x0): multiple definition of `strnlen_ss'
CMakeFiles/SvtVp9EncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `pa_get_block_stats':
(.text+0x0): multiple definition of `eb_start_time'
CMakeFiles/SvtVp9EncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `pa_get_block_stats':
(.text+0x0): multiple definition of `eb_finish_time'
CMakeFiles/SvtVp9EncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `pa_get_block_stats':
(.text+0x0): multiple definition of `eb_compute_overall_elapsed_time'
CMakeFiles/SvtVp9EncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Source/App/CMakeFiles/SvtVp9EncApp.dir/build.make:225: recipe for target '../../../Bin/Release/SvtVp9EncApp' failed
make[3]: *** [../../../Bin/Release/SvtVp9EncApp] Error 1
CMakeFiles/Makefile2:475: recipe for target 'Source/App/CMakeFiles/SvtVp9EncApp.dir/all' failed
make[2]: *** [Source/App/CMakeFiles/SvtVp9EncApp.dir/all] Error 2
CMakeFiles/Makefile2:487: recipe for target 'Source/App/CMakeFiles/SvtVp9EncApp.dir/rule' failed
make[1]: *** [Source/App/CMakeFiles/SvtVp9EncApp.dir/rule] Error 2
Makefile:255: recipe for target 'SvtVp9EncApp' failed
>
Any idea how to do this?
If i build it without the `-- BUILD_SHARED_LIBS = off` and change it to on it build okay.. but it's just much more convenient to have it static...

**Comment by 1480c1** [comment]
Currently, static lib support has not been added to SVT-VP9 yet

**Comment by ariffinsetya** [comment]
Oh, I'll wait for it then

**Comment by 1480c1** [comment]
It's probably best to keep an issue open until it's addressed. Plus if it's open, it's easier for others to spot it too and append to it rather than creating a new duplicate
