### ISSUE TITLE
YV12 chroma channels swapped

### ISSUE THREAD

**Issue by tg--** [OpenVisualCloud/SVT-VP9#60]
I've tried to encode a YV12 export, created with avidemux.
The exported file is a avidemux YV12 raw video file.
Encoding works fine, but the chroma channels appear to be swapped (blue is red, red is blue).

I've attached a single frame from the YV12 (raw) file and the encoded vp9 file.
Also attached is out.txt for the output of:
`SvtVp9EncApp -i frame.raw -b frame.vp9 -w 1920 -h 1080 -fps 30 -q 60 `

The version used is the latest git, 68b81bde77b8abca2fad5870d370b17258c976fc

[frame.raw.gz](https://github.com/OpenVisualCloud/SVT-VP9/files/3649825/frame.raw.gz)
[frame.vp9.gz](https://github.com/OpenVisualCloud/SVT-VP9/files/3649826/frame.vp9.gz)
[out.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/3649827/out.txt)

**Comment by Austin-Hu** [comment]
Hi @tg-- , SVT-VP9 encoder only supports YUV420 input format, and please refer to the user's [guide](https://github.com/OpenVisualCloud/SVT-VP9/blob/master/Docs/svt-vp9_encoder_user_guide.md#input-video-format). Thanks!
