### ISSUE TITLE
Reworked on the repo and retag the release

### ISSUE THREAD

**Issue by tianjunwork** [OpenVisualCloud/SVT-VP9#62]
Hi @EwoutH @kylophone @intelmark, PR is not "squash and merge" into the repo, git history looks very ugly. I rebased the repo and force pushed. Sorry to have to delete the tag you added. I will retag after adding '--version' to sample app next week. Apologies for any inconvenience.

**Comment by intelmark** [comment]
@tianjunwork Appreciate your attention to detail. Will be sure to squash and merge future PRs.

**Comment by tianjunwork** [comment]
Hi @intelmark, fyi PR `merge` is disabled for now for SVT-HEVC and SVT-VP9.

**Comment by tianjunwork** [comment]
Hi folks, apologies for the inconvenience again. SVT-VP9 is re-tagged v0.1.0.
