### ISSUE TITLE
ffmpeg "Too many invisible frames" issue still exists for mp4 

### ISSUE THREAD

**Issue by xiaotiansf** [OpenVisualCloud/SVT-VP9#84]
While ffmpeg "Too many invisible frames" issue has been fixed for mkv and webm. But it still exists for mp4. 
It can easily reproduced by the following test command in ffmpeg release/4.2.
./ffmpeg -i input.mp4 -vframes 1000 -c:v libsvt_vp9 -y test.mp4

**Comment by tianjunwork** [comment]
Thanks for your feedback. Yeah, mp4 is not fixed yet. We will work on it.

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925, webm/mkv is fixed. Could you fix mp4 also? Please refer to https://github.com/OpenVisualCloud/SVT-VP9/pull/80 for the fix. Thank you.
