### ISSUE TITLE
Dash-player does not play back ffmpeg vs (libsvt_vp9) dash encoder's segment mpd  

### ISSUE THREAD

**Issue by xiaotiansf** [OpenVisualCloud/SVT-VP9#89]
while I have confirmed that ffmpeg-master: Worked around the "Too many invisible frames" issue for mp4 has been fixed. SVT_VP9 encoder generated mp4 file now can be played back correctly.

ffmpeg dash encoded segment mpd (using svt_vp9) does not play back. I think something in "dashenc.c" needs to be patched much like the patch in "movenc.c".

**Comment by tianjunwork** [comment]
Hi @xiaotiansf , thank you confirming the fix.
Could you share with me the ffmpeg command which uses dashenc? Thank you.

**Comment by xiaotiansf** [comment]
Here is the test streaming script:
[stream-from-camera-svtvp9-test.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4202135/stream-from-camera-svtvp9-test.txt)
It needs to build ffmpeg from the fork: https://github.com/xiaotiansf/FFmpeg/tree/exmg-lls
and use the following dash-player to test:
http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html with the content link
https://exmachina-ull-demo.akamaized.net/cmaf/live/2009574/joep10/out.mpd

**Comment by tianjunwork** [comment]
Thank you @xiaotiansf , can anyone access`"http://test:Test123!@p-ep$stream_id.i.akamaientrypoint.net/cmaf/$stream_id/joep10" `?
If not, can we setup a local environment?

**Comment by xiaotiansf** [comment]
I think so. This is just for test purpose.

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925  Jiansheng, could you also look into the support for dashenc? Thank you.

**Comment by joepadmiraal** [comment]
We'll keep the test ingest address available for a while so you can test this.

**Comment by guojiansheng0925** [comment]
Hi @xiaotiansf, there is no camera in my machine. So I revised the test script to use a local mp4 file with x264 encode, but the dash player said "Data update failed". And if I use svt-vp9 encoder, it stuck or crashed.  Could you please help to check the FFmpeg command line in the script? Thank you.
[test_x264_sh.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4214023/test_x264_sh.txt)

**Comment by xiaotiansf** [comment]
@guojiansheng0925 Here is the script to just use test video without using camera.
[stream-from-file-svtvp9-test.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4215334/stream-from-file-svtvp9-test.txt)

**Comment by guojiansheng0925** [comment]
Hi @xiaotiansf, thank you for your reply. And I have other two question:
1 Could you please tell more detail about this issue? The dash-player report any error message?
2 If I replace libsvt_vp9 with libx264 in the test script, should it work properly? If it doesn't work, does it indicate there is something wrong with my local environment?

**Comment by xiaotiansf** [comment]
@guojiansheng0925  here are the two updated scripts (removed audio, changed to use .m4s) (one for SVT_VP9 and one for h264).
The h264 plays back on dash-player while SVT_VP9 does not.

[stream-from-file-h264-test.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4221029/stream-from-file-h264-test.txt)
[stream-from-file-svtvp9-test.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4221030/stream-from-file-svtvp9-test.txt)

**Comment by xiaotiansf** [comment]
@guojiansheng0925 To help you debug and compare, here is the working script (dash-player can playback) using libvpx-vp9 instead of libsvt_vp9.

[stream-from-file-vp9-test.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/4226809/stream-from-file-vp9-test.txt)

**Comment by guojiansheng0925** [comment]
Hi @xiaotiansf, we can confirm with the following command:
./ffmpeg -i input.mp4 -c:v libsvt_vp9 -f dash test.mpd
./ffmpeg -i test.mpd -vcodec copy -f mp4 outsvt.mp4

**Comment by joepadmiraal** [comment]
Cool.
So you are now able to test locally?
Can I remove the test stream?

**Comment by guojiansheng0925** [comment]
Sure, if xiaoxian doesn't need it too.

**Comment by xiaotiansf** [comment]
That's nice to know. test scripts are removed.
