### ISSUE TITLE
Added Visual Studio 16 2019 build support 

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-VP9#93]
@1480c1  
I remember that the patch in SVT-HEVC is the code you wrote. When do you have time to add it to SVT-VP9?

**Comment by 1480c1** [comment]
Are you talking about the build.bat?

**Comment by tnti** [comment]
@1480c1  Yes!

**Comment by 1480c1** [comment]
I have a vague feeling that you should be able to copy svt-hevc's build.bat into Build/windows folder and run it from there with no problems

**Comment by tnti** [comment]
The build.bat in svt-av1 can be copied directly into SVT-VP9, with only a few modifications.

**Comment by 1480c1** [comment]
Sure in a little bit

**Comment by tnti** [comment]
@1480c1 Thank you.

**Comment by 1480c1** [comment]
It's best to leave an issue open until it's fully addressed

**Comment by tnti** [comment]
Ok.
