### ISSUE TITLE
Playback errors caused by mp4box streaming.

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-VP9#94]
Sample command line：
@echo off
CD /D "%~dp0"
"E:\GPAC\mp4box.exe" -add "%~dpn1.ivf#trackID=1:fps=23.976:par=1:1:name=" -add "%~dpn1.aac#trackID=1:lang=jpn:name=" -tmp "D:\\" -new "%~dpn1.mp4"

It is known that modifying the timestamp in MKVToolNix will cause similar errors.
Cause the player to Caton.

Sample command line：
"C:/Program Files/MKVToolNix\mkvmerge.exe" --ui-language zh_CN --output ^"C:\Users\Administrator\Downloads\VP9.mkv^" --language 0:und --default-duration 0:24000/1001p ^"^(^" ^"C:\Users\Administrator\Downloads\VP9.ivf^" ^"^)^"

@tianjunwork

**Comment by tianjunwork** [comment]
Hi @tnti , I don't quite follow. What is wrong with SVT-VP9?

**Comment by tnti** [comment]
There may be errors in the timestamp after mux.
These tools have compatibility issues with the SVT-VP9 code stream.
The libvpx code stream does not have these problems.

**Comment by tianjunwork** [comment]
Hi @tnti , could you help answer below questions?
1. How did you generate the vp9.ivf file. What is the command line.
2. What are the steps to reproduce your issue? Which tool and command line?

**Comment by tnti** [comment]
Later I will pack a compressed package and upload it to the network disk, which contains the complete operation batch and the encoded code stream.
MKVToolNix and mp4box will have problems when modifying the frame rate. 
This bug has existed in the earlier SVT-VP9.

**Comment by tnti** [comment]
The archive contains all the batches and files. @tianjunwork 
https://ws28.cn/f/23iwjwpvtl0

**Comment by tianjunwork** [comment]
Hi @tnti , could you help answer below questions?

How did you generate the vp9.ivf file. What is the command line?
What are the detailed steps to reproduce your issue?

**Comment by tnti** [comment]
The zip pack contains everything you need.
@tianjunwork

**Comment by tnti** [comment]
SVT-VP9_y4m.bat was used.

**Comment by tianjunwork** [comment]
there are 3 bat files in the package, could you be specific about the steps to reproduce?

**Comment by tnti** [comment]
1. Generate .ifv using SVT-VP9_y4m.bat
2.use mp4box.bat mux
The mp4 file using ffmpeg mux has compatibility issues with VLC Android.

**Comment by tianjunwork** [comment]
Then what should I expect? and what is the issue with SVT-VP9 caused it? Please describe it all at once.

**Comment by tnti** [comment]
Perhaps there is a problem with DTS / PTS.

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925 , Could you verify ffmpge svt-vp9 DTS/PTS? Thank you. There is a package in https://github.com/OpenVisualCloud/SVT-VP9/issues/94#issuecomment-602046958.

**Comment by guojiansheng0925** [comment]
Hi @tianjunwork , sorry for the late reply.
I have downloaded the package and reproduce the issue on windows system. 
I don't think it's an issue of FFmpeg svt-vp9 plugin, We can simplified it with following command:

.\SvtVp9EncApp.exe -i .\test.yuv -enc-mode 6 -bit-depth 8 -w 1280 -h 720 -intra-period 240 -irefresh-type 2 -q 16 -rc 0 -fps-num 24000 -fps-denom 1001 -n 200 -b out.ivf

And the out.ivf can not playback well by VLC media player.

**Comment by tianjunwork** [comment]
@guojiansheng0925, thank you for simplifying the issue here👍. Maintainer will take a look with this command.

**Comment by tianjunwork** [comment]
Hi @tnti , I wonder why do you need to generate ivf first. Could you use our ffmpeg plugin and generate mkv directly?

**Comment by tianjunwork** [comment]
![image](https://user-images.githubusercontent.com/4551215/78200304-114b4d80-7443-11ea-9d09-ff1d4cdab7df.png)
I think the playback issue is because the 2nd `displayed` frame has a time code of 250, which in normal case should be 42. Frames are delayed by player before rendering it. And lots of frames are dropped because "main warning: picture is too late to be displayed"(vlc log).

Whichever tool you used to generate mkv seems not take into consideration of the `not displayed` frames when write time code.

Please use the ffmpeg plugin this repo to generate mkv directly.

**Comment by tnti** [comment]
Ok.
